### PR TITLE
Fix ore-dict based matching in PartyInventory

### LINKED ISSUE #147: OreDict item quests no longer working properly
As of version 4.2.7, OreDict detection no longer works. The following quest does not accept acacia/dark oak logs (logs not sharing the same item as the oak wood I put in) on the default retrieval settings:

Image

### PR DESCRIPTION
**Pull request by jchung01**
`PartyInventory` was not actually accounting for retrieval tasks that had ore-dict specified, just the base stack. This checks the hash of all stacks in the ore-dict when necessary to get the corresponding party's matching stacks.
~~Switched to using `RecipeItemHelper#pack()` for hashing.~~
Fixes #147.

### CODE REVIEW

**Review by WaitingIdly — APPROVED** [review]

File: src/main/java/betterquesting/questing/party/PartyInventory.java [hunk 1]
```diff
@@ -100,8 +100,18 @@ public PartyInventory(EntityPlayer mainPlayer, List<EntityPlayer> party) {
...
 
-        // The stacks matched by Item
-        var subStacks = gatheredStacks.get(req.getHashKey());
+        List<IndexedItemStack> subStacks = null;
+        if (req.hasOreDict()) {
+            // Stacks matched by any ore-dict item
+            for (ItemStack oreStack : req.getOreIngredient().getMatchingStacks()) {
+                int itemHash = BigItemStack.getHashKey(oreStack);
+                subStacks = gatheredStacks.get(itemHash);
+                if (subStacks != null) break;
```
Comment (WaitingIdly) [inline src/main/java/betterquesting/questing/party/PartyInventory.java]:
```suggestion
            subStacks = new ArrayList<>();
            // Stacks matched by any ore-dict item
            for (ItemStack oreStack : req.getOreIngredient().getMatchingStacks()) {
                int itemHash = BigItemStack.getHashKey(oreStack);
                var local = gatheredStacks.get(itemHash);
                if (local != null) subStacks.addAll(local);
````

**Review by WaitingIdly — CHANGES_REQUESTED** [review]

**Review by WaitingIdly — APPROVED** [review]
